# -*- coding: utf-8 -*-
"""Ilari&Casper_project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z7IVX9UXcJRRUUXHTUw7UXTLc1oJgvRz
"""

import statsmodels.formula.api as smf
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv(r'/content/asset_gdp_correlation.csv')

reg = smf.ols('eu_assets ~ eu_gdp', data=data)

reg = reg.fit()

reg.summary()

print(reg.summary())

x=[55987549.2, 56697279.4, 62620989.9, 66764546.7, 70023748.5, 71650104.2
, 72065639.7, 78598388.3]

y=[29552, 29471, 29861, 30485, 31031, 31855, 32460, 33032]

z=[2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]

plt.xlabel("Total EU Assets")
plt.ylabel("GDP")
plt.plot(x,y)
plt.show()
plt.xlabel("Year")
plt.ylabel("GDP")
plt.plot(z,y)
plt.show()
plt.xlabel("Year")
plt.ylabel("Total Assets")
plt.plot(z,x)
plt.show()

